# Generated by Django 3.2.18 on 2023-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(unique=True)),
                ('user_id', models.IntegerField(default=0, max_length=255)),
                ('type', models.CharField(default='', max_length=255)),
                ('params', models.JSONField(default={})),
                ('status', models.CharField(default='pending', max_length=255)),
                ('status_detail', models.TextField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
