# Generated by Django 3.2.18 on 2023-04-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_scriptjobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptjobs',
            name='params',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='scriptjobs',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
