# Generated by Django 3.2.18 on 2023-04-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20230427_1833'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScriptJobs',
            new_name='ScriptJob',
        ),
    ]
